twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
      frontend_domain: '//%env(FRONTEND_DOMAIN)%'
    form_themes:
      - 'form/custom_types.html.twig'
