version: '3.4'
services:
    php:
        container_name: blog-php-fpm
        build: ./services/php-fpm
        volumes:
            - ../app:/var/www/
            - media:/var/www/admin/symfony/public/media
            - ./shared:/docker-shared
        environment:
            - SERVER_ENV
        tty: true
    node:
        container_name: blog-node
        build: ./services/node
        volumes:
            - ../app:/var/www
            - ./shared:/docker-shared
        command: /root/bin/watch.sh
        tty: true
        environment:
            - SERVER_ENV
    proxy:
        container_name: blog-proxy
        build: ./services/proxy
        ports:
            - "${PROXY_HTTP_PORT}:80"
            - "${PROXY_HTTPS_PORT}:443"
        volumes:
            - certificates:/etc/nginx/certificates
            - ./shared:/docker-shared
        depends_on:
            - php
            - frontend
            - admin
            - api
            - media
        tty: true
        command: nginx -g 'daemon off;'
    frontend:
        container_name: blog-frontend
        build: ./services/frontend
        volumes:
            - ../app:/var/www
            - ./services/frontend/etc/nginx/sites-available:/etc/nginx/sites-available
            - ./services/frontend/etc/nginx/sites-available:/etc/nginx/sites-enabled
            - ./shared:/docker-shared
        working_dir: /var/www/frontend
        depends_on:
            - node
    admin:
        container_name: blog-admin
        build: ./services/admin
        volumes:
            - ../app:/var/www
            - media:/var/www/admin/symfony/public/media
            - ./services/admin/etc/nginx/sites-available:/etc/nginx/sites-available
            - ./services/admin/etc/nginx/sites-available:/etc/nginx/sites-enabled
            - ./shared:/docker-shared
        tty: true
        working_dir: /var/www/admin
        depends_on:
            - php
    api:
        container_name: blog-api
        build: ./services/api
        volumes:
            - ../app:/var/www
            - ./services/api/etc/nginx/sites-available:/etc/nginx/sites-available
            - ./services/api/etc/nginx/sites-available:/etc/nginx/sites-enabled
            - ./shared:/docker-shared
        tty: true
        working_dir: /var/www/api
        depends_on:
            - php
    dbserver:
        container_name: blog-dbserver
        image: mariadb
        volumes:
            - dbserver:/var/lib/mysql
        ports:
            - "${DB_PORT}:3306"
        environment:
            - MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
    media:
        container_name: blog-media
        build: ./services/media
        volumes:
            - media:/var/www
            - ./services/media/etc/nginx/sites-available:/etc/nginx/sites-available
            - ./services/media/etc/nginx/sites-available:/etc/nginx/sites-enabled
            - ./shared:/docker-shared
volumes:
    dbserver:
    media:
    certificates:
        external:
            name: blog-certificates
