vich_uploader:
    db_driver: orm

    mappings:
      asset:
        uri_prefix: ''
        upload_destination: '%kernel.project_dir%/public/media'
        directory_namer: Core\Library\Upload\DirectoryNamer
